language: java
jdk:
    - oraclejdk8

before_install:

# Install LibreOffice
- sudo apt-get update
- sudo apt-get install -y libreoffice-writer webp imagemagick

# Install elasticsearch
- wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.1.zip
- unzip elasticsearch-1.7.1.zip
- elasticsearch-1.7.1/bin/elasticsearch -d

# Gradle
- echo "bintrayUser=''" >> gradle.properties
- echo "bintrayKey=''" >> gradle.properties

after_script:
# Shutdown elasticsearch daemon
- curl -i -XPOST 'http://localhost:9200/_shutdown'
- cat /home/travis/build/saw303/dox/web/build/reports/tests/integrationTest/integration/index.html

cache:
  directories:
  - $HOME/.gradle
