language: java
jdk:
    - oraclejdk7
	- oraclejdk8
    - openjdk7

env:
    - DOX_STORE=~

before_install:

# Gradle
- wget http://services.gradle.org/distributions/gradle-1.10-bin.zip
- unzip gradle-1.10-bin.zip
- export GRADLE_HOME=$PWD/gradle-1.10
- export PATH=$GRADLE_HOME/bin:$PATH
- gradle -version
