# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

language: java
jdk:
    - oraclejdk7
    - oraclejdk8
    - openjdk7

env:
    - DOX_STORE=~

before_install:

# Install LibreOffice
- sudo apt-get update
- sudo apt-get install libreoffice-writer
# Gradle
- wget http://services.gradle.org/distributions/gradle-2.2.1-bin.zip
- unzip gradle-2.2.1-bin.zip
- export GRADLE_HOME=$PWD/gradle-2.2.1
- export PATH=$GRADLE_HOME/bin:$PATH
- gradle -version
