language: java
jdk:
    - oraclejdk8

env:
    - DOX_STORE=~

before_install:

# Install LibreOffice
- sudo apt-get update
- sudo apt-get install -y libreoffice-writer

# Install elasticsearch
- wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.1.zip
- unzip elasticsearch-1.7.1.zip
- elasticsearch-1.7.1/bin/elasticsearch -d

# Gradle
- wget http://services.gradle.org/distributions/gradle-2.5-bin.zip
- unzip gradle-2.5-bin.zip
- export GRADLE_HOME=$PWD/gradle-2.5
- export PATH=$GRADLE_HOME/bin:$PATH
- gradle -version
- touch gradle.properties
- echo "bintrayUser=''" >> gradle.properties
- echo "bintrayKey=''" >> gradle.properties

after_script:
# Shutdown elasticsearch daemon
- curl -i -XPOST 'http://localhost:9200/_shutdown'
