sudo: false
language: java
jdk:
    - oraclejdk8

env:
    - DOX_STORE=~

addons:
  apt:
    packages:
    - libreoffice-writer
    - imagemagick
    - webp

before_install:
# Install elasticsearch
- wget https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.7.1.zip
- unzip elasticsearch-1.7.1.zip
- elasticsearch-1.7.1/bin/elasticsearch -d

# Gradle
- touch gradle.properties
- echo "bintrayUser=''" >> gradle.properties
- echo "bintrayKey=''" >> gradle.properties

after_script:
# Shutdown elasticsearch daemon
- curl -i -XPOST 'http://localhost:9200/_shutdown'
