language: java
jdk:
    - oraclejdk7
    - openjdk7

env:
    - DOX_STORE=~

before_install:

# Gradle
- wget http://services.gradle.org/distributions/gradle-1.6-bin.zip
- unzip gradle-1.6-bin.zip
- export GRADLE_HOME=$PWD/gradle-1.6
- export PATH=$GRADLE_HOME/bin:$PATH
- gradle -version

after_script:

- ls -l $TRAVIS_TEST_RESULT
- cd $TRAVIS_TEST_RESULT
- pwd