language: java
jdk:
    - oraclejdk7
    - oraclejdk8
    - openjdk7

env:
    - DOX_STORE=~

before_install:

# Install LibreOffice
- sudo apt-get update
- sudo apt-get install libreoffice-writer
# Gradle
- wget http://services.gradle.org/distributions/gradle-2.5.0-bin.zip
- unzip gradle-2.5.0-bin.zip
- export GRADLE_HOME=$PWD/gradle-2.5.0
- export PATH=$GRADLE_HOME/bin:$PATH
- gradle -version
- touch gradle.properties
- echo "bintrayUser=''" >> gradle.properties
- echo "bintrayKey=''" >> gradle.properties
