== Installation Guide

=== Hardware Requirements

[cols="2,5a"]
|===
| Category | Requirements
|RAM
|At least 640 MB free RAM
|Disk
|200 MB free disk space (and some more disk space for the documents you want to store in DOX)
|===

=== Software Requirements

[cols="2,5a"]
|===
| Category | Requirements
|Database
|The following databases are supported:

* MySQL 5.6 (or above)
* MariaDB 10.x

The following will most likely work with DOX but have not been tested.

* Oracle
* IBM DB2
* Microsoft SQL Server
* Postgres

| Java Environment
| Java 8 (or above)
| Servlet Engine
| Tomcat 8, Jetty (not tested)
| Image Processing
| http://imagemagick.org/[ImageMagick] or http://www.graphicsmagick.org/[GraphicsMagick]
| Office Suite
| http://www.libreoffice.org/[LibreOffice]
| HTTP Server (Optional)
| Use one of the following webserver a reverse proxy

* http://nginx.org/[Nginx]
* http://httpd.apache.org/[Apache 2.4]
|===

=== Server Installation

==== Install third party software

===== Install MySQL 5.6
DOX uses Hibernate 4.x to interact with a relational database. I recommend to use MySQL 5.6 (or greater).

	sudo apt-get install mysql-server-5.6

===== Install latest stable Nginx
Install add-apt-repository Python script.
	
	sudo apt-get install python-software-properties
	sudo apt-get install software-properties-common

Then install the Nginx PPA repo.

	sudo add-apt-repository ppa:nginx/stable
	sudo apt-get update
	sudo apt-get install nginx

===== Install Java 8

	sudo add-apt-repository ppa:webupd8team/java
	sudo apt-get update
	sudo apt-get install oracle-java8-installer

===== Install Apache Tomcat 8
tbd

===== Install ImageMagick/GraphicsMagick & webp

DOX uses ImageMagick to create thumbnails. In order to decrease the amount of image data that is transfered from the server to the browser DOX uses Google's WEBP format.

    sudo apt-get install imagemagick webp

In order to install Graphismagick instead of ImageMagick use

    sudp apt-get install graphicsmagick-imagemagick-compat webp

==== Install DOX
===== Setup the MySQL / MariaDB database
To set up the database for DOX you can the following DDL script `ddl_mysql5innodb_create.sql` for MySQL. You find the script
in the `domain.jar` of the WAR. Open the WAR file by using http://www.7-zip.org/download.html[7zip] (or some equal app) and navigate to

	/WEB-INF/lib/dox-domain-<version>.jar

To create the database 

	mysql -u root -p -e "CREATE DATABASE dox;"

The apply the DDL to the database `dox`

	mysql -u root -p dox < ddl_mysql5innodb_create.sql

====== Create a database user for the application

	GRANT ALL PRIVILEGES ON dox.* TO '<your dox database username>'@'localhost' IDENTIFIED BY '<your dox database password>';

===== Configure Apache Tomcat 8

====== Install your JDBC driver in

    <TOMCAT_HOME>/lib

====== Create JDNI datasource

DOX uses JDNI to lookup its connection to the database. The lookup name is called `jdbc/dox`. To configure the datasource edit the file `<TOMCAT_HOME>/conf/context.xml`.

[source,xml]
.context.xml
----
<Resource name="jdbc/dox" auth="Container"
          type="javax.sql.DataSource" driverClassName="com.mysql.jdbc.Driver"
          url="jdbc:mysql://localhost/dox"
          username="<your dox database username>" password="<your dox database password>"
          maxActive="20" maxIdle="10" maxWait="-1"/>
----

===== Deploy DOX

Copy the WAR file into `<TOMCAT_HOME>/webapps`

    cp dox-<version>.war <TOMCAT_HOME>/webapps/ROOT.war

Start Tomcat 

    <TOMCAT_HOME>/bin/startup.sh
