CREATE TABLE DOX_USER_SETTINGS (
  id      BIGINT       NOT NULL AUTO_INCREMENT,
  SET_KEY VARCHAR(255) NOT NULL,
  SET_VAL VARCHAR(255) NOT NULL,
  user_id BIGINT       NOT NULL,
  PRIMARY KEY (id)
)
  ENGINE =InnoDB;

ALTER TABLE DOX_USER_SETTINGS
ADD CONSTRAINT UK_DOX_USER_SETTINGS_1 UNIQUE (user_id, SET_KEY);

ALTER TABLE DOX_USER_SETTINGS
ADD INDEX FK58AED685818A99FB (user_id),
ADD CONSTRAINT FK58AED685818A99FB
FOREIGN KEY (user_id)
REFERENCES DOX_USER (id);