ALTER TABLE DOX_IDX_STORE ADD COLUMN LD_01 DATE;
ALTER TABLE DOX_IDX_STORE ADD COLUMN LD_02 DATE;
ALTER TABLE DOX_IDX_STORE ADD COLUMN LD_03 DATE;
ALTER TABLE DOX_IDX_STORE ADD COLUMN LD_04 DATE;
ALTER TABLE DOX_IDX_STORE ADD COLUMN LD_05 DATE;

UPDATE DOX_IDX_STORE SET LD_01 = D_01 WHERE D_01 IS NOT NULL;
UPDATE DOX_IDX_STORE SET D_01 = NULL WHERE LD_01 IS NOT NULL;
UPDATE DOX_IDX_STORE SET LD_02 = D_02 WHERE D_02 IS NOT NULL;
UPDATE DOX_IDX_STORE SET D_02 = NULL WHERE LD_02 IS NOT NULL;
UPDATE DOX_IDX_STORE SET LD_03 = D_03 WHERE D_03 IS NOT NULL;
UPDATE DOX_IDX_STORE SET D_03 = NULL WHERE LD_03 IS NOT NULL;
UPDATE DOX_IDX_STORE SET LD_04 = D_04 WHERE D_04 IS NOT NULL;
UPDATE DOX_IDX_STORE SET D_04 = NULL WHERE LD_04 IS NOT NULL;
UPDATE DOX_IDX_STORE SET LD_05 = D_05 WHERE D_05 IS NOT NULL;
UPDATE DOX_IDX_STORE SET D_05 = NULL WHERE LD_05 IS NOT NULL;

ALTER TABLE DOX_ATTR MODIFY COLUMN mappingColumn varchar(5) not null;

UPDATE DOX_ATTR SET mappingColumn = 'LD_01' WHERE shortName = 'invoiceDate';
UPDATE DOX_ATTR SET mappingColumn = 'LD_02' WHERE shortName = 'taxDate';
UPDATE DOX_ATTR SET mappingColumn = 'LD_03' WHERE shortName = 'salaryDate';