ALTER TABLE DOX_IDX_STORE ADD COLUMN C_01 VARCHAR(255);
ALTER TABLE DOX_IDX_STORE ADD COLUMN C_02 VARCHAR(255);
ALTER TABLE DOX_IDX_STORE ADD COLUMN C_03 VARCHAR(255);
ALTER TABLE DOX_IDX_STORE ADD COLUMN C_04 VARCHAR(255);
ALTER TABLE DOX_IDX_STORE ADD COLUMN C_05 VARCHAR(255);
ALTER TABLE DOX_IDX_STORE ADD COLUMN C_06 VARCHAR(255);
ALTER TABLE DOX_IDX_STORE ADD COLUMN C_07 VARCHAR(255);
ALTER TABLE DOX_IDX_STORE ADD COLUMN C_08 VARCHAR(255);
ALTER TABLE DOX_IDX_STORE ADD COLUMN C_09 VARCHAR(255);
ALTER TABLE DOX_IDX_STORE ADD COLUMN C_10 VARCHAR(255);

UPDATE DOX_ATTR
SET dataType = 'CURRENCY', mappingColumn = 'C_01'
WHERE shortName = 'invoiceAmount' AND mappingColumn = 'F_01';
UPDATE DOX_ATTR
SET dataType = 'CURRENCY', mappingColumn = 'C_02'
WHERE shortName = 'salaryAmount' AND mappingColumn = 'F_02';

UPDATE DOX_IDX_STORE t1
SET C_01 = CONCAT('CHF ', F_01), F_01 = NULL;
UPDATE DOX_IDX_STORE t1
SET C_02 = CONCAT('CHF ', F_02), F_02 = NULL;