CREATE TABLE DOX_DOC_DOX_TAG (
  DOX_DOC_id BIGINT NOT NULL,
  tags_id    BIGINT NOT NULL,
  PRIMARY KEY (DOX_DOC_id, tags_id)
)
  ENGINE = InnoDB;

CREATE TABLE DOX_TAG (
  id   BIGINT      NOT NULL AUTO_INCREMENT,
  name VARCHAR(15) NOT NULL,
  PRIMARY KEY (id)
)
  ENGINE = InnoDB;

ALTER TABLE DOX_TAG
ADD CONSTRAINT UK_mlfcxh1p6w7djmt63b9il63hm UNIQUE (name);

ALTER TABLE DOX_DOC_DOX_TAG
ADD CONSTRAINT FK_mcyfmg5yn1e4u8t4vbtps0i7l
FOREIGN KEY (tags_id)
REFERENCES DOX_TAG (id);

ALTER TABLE DOX_DOC_DOX_TAG
ADD CONSTRAINT FK_8vw5v1m39u0vwy7765v2sxyiy
FOREIGN KEY (DOX_DOC_id)
REFERENCES DOX_DOC (id);